// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://tqsrqwughplknttckjaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxc3Jxd3VnaHBsa250dGNramF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzUyMTAsImV4cCI6MjA2MjExMTIxMH0.fGwbAPl2utNwlyTLor9OsHbChBJl49NfHwVJLuL557A";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);